# Setup
title:               IFT6758 Blog
tagline:             'Data-Driven Insights from the Rink'
description:         'Dive into the world of NHL hockey through the lens of data analytics. Made by Yue Xin Li, Yihang Huang, Serge Malo and Arvind Nair.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author1:
  name1:              Yue Xin Li
  #  url:               https://twitter.com/mdo
  email1:             yue.xin.li@umontreal.ca

author2:
  name:              Yihang Huang
  #  url:               https://twitter.com/mdo
  email2:             yihang.huang@umontreal.ca

author3:
  name:              Serge Malo
  #  url:               https://twitter.com/chairze
  email3:             serge.malo@umontreal.ca

author4:
  name:              Arvind Nair
  #  url:               https://twitter.com/mdo
  email4:             arvind.nair@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
